### PR TITLE
Add more filters, order bys to the report, also bump version 

### PR DESCRIPTION
**Pull request by eileenmcnaughton**
@seamuslee001 ...

### CODE REVIEW

**Comment by eileenmcnaughton** [comment]
@seamuslee001 just added another commit in here :-)

**Comment by eileenmcnaughton** [comment]
Just added a boilerplate update

**Comment by eileenmcnaughton** [comment]
just ran the civix upgrade

**Comment by eileenmcnaughton** [comment]
@johntwyman I realise this is only marginally maintained but I just investigated a deprecation warning & fixed it

**Comment by johntwyman** [comment]
Thanks @eileenmcnaughton!

**Comment by eileenmcnaughton** [comment]
@johntwyman this might win longest running PR ever - I just added another update  -7 years after the first one!

**Review by johntwyman — APPROVED** [review]

**Comment by johntwyman** [comment]
@eileenmcnaughton clearly I was waiting for Entity Framework v2.

**Comment by eileenmcnaughton** [comment]
And now it is here!

**Pull request merged**
